name: Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@latest
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci
        run: npm ci
      - name: Run tests
        run: npm run test-all
